POST http://localhost:3000/auth/register HTTP/1.1
Content-Type: application/json

{
    "email": "ryanla94@gmail.com",
    "name": "Ryan",
    "password": "Password123"
}

###
POST http://localhost:3000/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "ryanla94@gmail.com",
    "password": "Password123"
}

###
POST http://localhost:3000/portfolio/ HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3000/portfolio/0595ae83-c94f-4275-8fc5-bc3e9b7ff25a HTTP/1.1
Content-Type: application/json

###
DELETE http://localhost:3000/portfolio/0595ae83-c94f-4275-8fc5-bc3e9b7ff25a HTTP/1.1

###
GET http://localhost:3000/portfolio/0595ae83-c94f-4275-8fc5-bc3e9b7ff25a/assets/stocks/ HTTP/1.1

###
POST http://localhost:3000/portfolio/0595ae83-c94f-4275-8fc5-bc3e9b7ff25a/assets/stocks/ HTTP/1.1
Content-Type: application/json

{
    "name": "Amazon.com, Inc.",
    "ticker": "AMZN",
    "quantity": 10
}

###
PATCH http://localhost:3000/portfolio/0595ae83-c94f-4275-8fc5-bc3e9b7ff25a/assets/stocks/9d4affe5-dfea-461a-bbed-8bb424616019/ HTTP/1.1
Content-Type: application/json

{
    "name": "Apple Inc.",
    "ticker": "AAPL",
    "quantity": 15
}

###
DELETE http://localhost:3000/portfolio/0595ae83-c94f-4275-8fc5-bc3e9b7ff25a/assets/stocks/9d4affe5-dfea-461a-bbed-8bb424616019/ HTTP/1.1