POST http://localhost:3000/auth/register HTTP/1.1
Content-Type: application/json

{
    "email": "ryanla94@gmail.com",
    "name": "Ryan",
    "password": "Password123"
}

###
POST http://localhost:3000/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "ryanla94@gmail.com",
    "password": "Password123"
}

###
GET http://localhost:3000/auth/me HTTP/1.1

###
POST http://localhost:3000/portfolio/ HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3000/portfolio/2023ebcc-fde8-437c-be49-efa4b50b475c HTTP/1.1
Content-Type: application/json

###
DELETE http://localhost:3000/portfolio/2023ebcc-fde8-437c-be49-efa4b50b475c HTTP/1.1

###
GET http://localhost:3000/portfolio/2023ebcc-fde8-437c-be49-efa4b50b475c/assets/stocks/ HTTP/1.1

###
POST http://localhost:3000/portfolio/2023ebcc-fde8-437c-be49-efa4b50b475c/assets/stocks/ HTTP/1.1
Content-Type: application/json

{
    "name": "Amazon.",
    "ticker": "AAPL",
    "quantity": 5
}

###
PATCH http://localhost:3000/portfolio/2023ebcc-fde8-437c-be49-efa4b50b475c/assets/stocks/868a97b3-385f-4007-9a42-852e2ea3fe5d/ HTTP/1.1
Content-Type: application/json

{
    "name": "Apple Inc.",
    "ticker": "AAPL",
    "quantity": 8
}

###
DELETE http://localhost:3000/portfolio/2023ebcc-fde8-437c-be49-efa4b50b475c/assets/stocks/868a97b3-385f-4007-9a42-852e2ea3fe5d/ HTTP/1.1

